spring.application.name=externalservices

spring.datasource.url=jdbc:mysql://localhost:3306/externalservices
spring.datasource.username=root
spring.datasource.password=Mysql@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
